# Generated by Django 3.2.8 on 2021-11-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrystandards',
            name='type',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='short_text',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='type',
        ),
        migrations.AddField(
            model_name='facts',
            name='citation',
            field=models.ManyToManyField(blank=True, null=True, to='monest.Citations'),
        ),
        migrations.AddField(
            model_name='news',
            name='citation',
            field=models.ManyToManyField(blank=True, null=True, to='monest.Citations'),
        ),
        migrations.AddField(
            model_name='politicalassociation',
            name='citation',
            field=models.ManyToManyField(blank=True, null=True, to='monest.Citations'),
        ),
        migrations.AddField(
            model_name='scores',
            name='citation',
            field=models.ManyToManyField(blank=True, null=True, to='monest.Citations'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='long_text',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monest.metrics')),
            ],
        ),
        migrations.AddField(
            model_name='industrystandards',
            name='metric',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monest.metrics'),
        ),
        migrations.AddField(
            model_name='scores',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monest.metrics'),
        ),
    ]
