# Generated by Django 3.2.8 on 2021-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monest', '0002_auto_20211113_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='citation',
            field=models.ManyToManyField(blank=True, to='monest.Citations'),
        ),
        migrations.AlterField(
            model_name='news',
            name='citation',
            field=models.ManyToManyField(blank=True, to='monest.Citations'),
        ),
        migrations.AlterField(
            model_name='politicalassociation',
            name='citation',
            field=models.ManyToManyField(blank=True, to='monest.Citations'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='citation',
            field=models.ManyToManyField(blank=True, to='monest.Citations'),
        ),
    ]
