# Generated by Django 3.2.8 on 2021-11-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monest', '0003_auto_20211113_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='long_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
