# Generated by Django 3.2.8 on 2021-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monest', '0005_alter_scores_long_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='author',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='citations',
            name='date',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='citations',
            name='pages',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='citations',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='citations',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
