# Generated by Django 3.2.8 on 2021-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monest', '0008_auto_20211113_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
