# Generated by Django 3.2.8 on 2022-01-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monest', '0012_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
