# Generated by Django 3.2.8 on 2022-02-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100)),
                ('price', models.FloatField(blank=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(max_length=300, unique=True)),
                ('photo', models.URLField(blank=True, max_length=300)),
            ],
        ),
    ]
