# Generated by Django 3.2.8 on 2022-02-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20220205_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_title',
            new_name='category',
        ),
    ]
