# Generated by Django 3.2.8 on 2022-02-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20220205_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descr',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
