# Generated by Django 3.2.8 on 2022-02-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_product_descr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='image',
        ),
    ]
