# Generated by Django 3.2.8 on 2022-02-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_auto_20220208_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
