# Generated by Django 4.0.2 on 2022-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0010_alter_product_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
